/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DigestIndexRouteImport } from './routes/digest.index'
import { Route as DigestSlugRouteImport } from './routes/digest.$slug'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestIndexRoute = DigestIndexRouteImport.update({
  id: '/digest/',
  path: '/digest/',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestSlugRoute = DigestSlugRouteImport.update({
  id: '/digest/$slug',
  path: '/digest/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/digest/$slug': typeof DigestSlugRoute
  '/digest/': typeof DigestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/digest/$slug': typeof DigestSlugRoute
  '/digest': typeof DigestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/digest/$slug': typeof DigestSlugRoute
  '/digest/': typeof DigestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/digest/$slug' | '/digest/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/digest/$slug' | '/digest'
  id: '__root__' | '/' | '/about' | '/digest/$slug' | '/digest/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DigestSlugRoute: typeof DigestSlugRoute
  DigestIndexRoute: typeof DigestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest/': {
      id: '/digest/'
      path: '/digest'
      fullPath: '/digest/'
      preLoaderRoute: typeof DigestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest/$slug': {
      id: '/digest/$slug'
      path: '/digest/$slug'
      fullPath: '/digest/$slug'
      preLoaderRoute: typeof DigestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DigestSlugRoute: DigestSlugRoute,
  DigestIndexRoute: DigestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
